import type { Metadata } from "next";
import "./globals.css";
import { SmoothScroll } from "@/components/smooth-scroll";
import ReduxProvider from "@/redux/provider/ReduxProvider";

import { inter } from "./fonts";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// test its added
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="font-sans antialiased">
        <ReduxProvider>
          <SmoothScroll>
            {children}
            <Toaster position="top-center" richColors/>
          </SmoothScroll>
        </ReduxProvider>
      </body>
    </html>
  );
}
