import type { Metadata } from "next";
import "./globals.css";
import { SmoothScroll } from "@/components/smooth-scroll";
import ReduxProvider from "@/redux/provider/ReduxProvider";

import { inter, jetbrainsMono } from "./fonts";
import { Header } from "@/components/header";
import { Toaster } from "sonner";
import { ChatWidget } from "@/components/chat/ChatWidget";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// test its added
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <body className="font-sans antialiased" suppressHydrationWarning>
        <ReduxProvider>
          <SmoothScroll>
            {children}
            <ChatWidget />
            <Toaster position="top-center" richColors />
          </SmoothScroll>
        </ReduxProvider>
      </body>
    </html>
  );
}
